namespace QuantoDemoraApi.Models.Enums
{
    public enum LogradouroEnum
    {
        Aeroporto = 1,
        Alameda = 2,
        Area = 3,
        Avenida = 4,
        Campo = 5,
        Chacara = 6,
        Colonia = 7,
        Condominio = 8,
        Conjunto = 9,
        Distrito = 10,
        Esplanada = 11,
        Estacao = 12,
        Estrada = 13,
        Favela = 14,
        Fazenda = 15,
        Feira = 16,
        Jardim = 17,
        Ladeira = 18,
        Lago = 19,
        Lagoa = 20,
        Largo = 21,
        Loteamento = 22,
        Morro = 23,
        Nucleo = 24,
        Parque = 25,
        Passarela = 26,
        Patio = 27,
        Praca = 28,
        Quadra = 29,
        Recanto = 30,
        Residencial = 31,
        Rodovia = 32,
        Rua = 33,
        Setor = 34,
        Sitio = 35,
        Travessa = 36,
        Trecho = 37,
        Trevo = 38,
        Vale = 39,
        Vereda = 40,
        Via = 41,
        Viaduto = 42,
        Viela = 43,
        Vila = 44
    }
}